apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubernetes.io/change-cause: kubectl apply --filename=deployment.yaml --record=true
  labels:
    name: order-context
  name: order-context
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: order-context
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: order-context
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: NACOS_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: order-context
        image: image_url
        imagePullPolicy: IfNotPresent
        name: order-context
        ports:
        - containerPort: 9080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 50m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config.yaml
          name: config-volume
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: test-secret
      initContainers:
      - args:
        - job
        - migrate-job
        # 等待job完成
        image: groundnuty/k8s-wait-for:1.3
        imagePullPolicy: IfNotPresent
        name: order-context-init
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: order-context
        name: config-volume