runmode: debug # 开发模式, debug, release, test
prefix_path: /api/
log:
  file: false
  logrus_json: true
  logrus_level: debug
  logrus_file: log/server.log
  logrus_console: true
  gin_file: log/gin.log
  gin_console: true
db:
  driver: postgres
  dsn: host=127.0.0.1 user=postgres password=123 dbname=order port=5432 sslmode=disable TimeZone=Asia/Shanghai
gormlog: true # gorm 的日志模式, true 是详细日志, false 不记录日志

uuidsrv:
  host: http://127.0.0.1:8181

addr: 127.0.0.1
port: 9080

http_port: 8018